version: '3.1'
services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
  postgres:
    image: 'postgres'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '2345:5432'
